# Generated by Django 5.1.1 on 2024-09-16 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_account_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='investment_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
