# Generated by Django 5.1.1 on 2024-09-16 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_account_investment_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='investment_value',
        ),
    ]
