# Generated by Django 5.1.1 on 2024-09-13 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_investment_remove_transaction_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='investment',
        ),
        migrations.RemoveField(
            model_name='interestreturn',
            name='investment',
        ),
        migrations.RemoveField(
            model_name='holding',
            name='investment',
        ),
        migrations.DeleteModel(
            name='Investment',
        ),
    ]
