# Generated by Django 5.1.1 on 2024-09-14 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_simulatedinvestment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='simulatedinvestment',
            options={'verbose_name': 'Investment', 'verbose_name_plural': 'Investments'},
        ),
    ]
