# Generated by Django 5.1.1 on 2024-09-14 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_account_balance'),
        ('transactions', '0006_alter_simulatedinvestment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='account',
            field=models.ForeignKey(default='none', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='investment',
            field=models.ForeignKey(default='none', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='transactions.simulatedinvestment'),
        ),
    ]
