# Generated by Django 5.1.1 on 2024-09-14 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_transaction_account_transaction_investment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulatedinvestment',
            name='price_per_unit',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
    ]
