# Generated by Django 5.1.1 on 2024-09-16 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_delete_holding'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulatedinvestment',
            name='investment_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
