# Generated by Django 5.1.1 on 2024-09-16 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0010_simulatedinvestment_investment_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simulatedinvestment',
            name='investment_amount',
        ),
    ]
