# Generated by Django 5.1.1 on 2024-09-16 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0011_remove_simulatedinvestment_investment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulatedinvestment',
            name='investment_type',
            field=models.CharField(choices=[('stock', 'Stock'), ('forex', 'Forex'), ('crypto', 'Cryptocurrency')], default='stock', max_length=10),
        ),
    ]
