# Generated by Django 5.1.1 on 2024-09-16 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0012_simulatedinvestment_investment_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simulatedinvestment',
            name='investment_type',
        ),
    ]
