# Generated by Django 5.1.1 on 2024-09-20 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0014_alter_simulatedinvestment_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='simulatedinvestment',
            unique_together=set(),
        ),
    ]
